[tool.poetry]
name = "nlp-with-transformers-book-my-notes"
version = "0.1.0"
description = ""
authors = ["Hamza B."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.51.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
